var serviceDatabase = {
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
                                                                                
"features": [
{ "type": "Feature", "properties": { "ServiceNam": "Adult Protection Services", "Address": "1165 Centre Parkway", "City": "Lexington", "State": "Kentucky", "ZipCode": "40517", "ServiceCat": "Abuse Counseling and Support", "AddtnlAddr": "Suite 180", "OperationH": null, "PrimaryPho": "859-245-7136", "SecondaryP": null, "Website": null, "addrtype": "street_address", "addrlocat": "ROOFTOP" }, "geometry": { "type": "Point", "coordinates": [ -84.482466, 37.98219 ] } },
{ "type": "Feature", "properties": { "ServiceNam": "Brenda Cowen Center", "Address": "1364 Devonport Drive", "City": "Lexington", "State": "Kentucky", "ZipCode": "40504", "ServiceCat": "Abuse Counseling and Support", "AddtnlAddr": null, "OperationH": null, "PrimaryPho": "859-276-4457", "SecondaryP": null, "Website": "www.cowancoalition.org", "addrtype": "street_address", "addrlocat": "ROOFTOP" }, "geometry": { "type": "Point", "coordinates": [ -84.553109, 38.048984 ] } },
{ "type": "Feature", "properties": { "ServiceNam": "Crysalis House", "Address": "251 E. Maxwell Street", "City": "Lexington", "State": "Kentucky", "ZipCode": "40508", "ServiceCat": "Residential Substance Abuse Help", "AddtnlAddr": null, "OperationH": null, "PrimaryPho": "859-231-6396", "SecondaryP": "Toll Free 1-800-713-0954 (Admissions)", "Website": "www.chrysalishouse.org", "addrtype": "street_address", "addrlocat": "ROOFTOP" }, "geometry": { "type": "Point", "coordinates": [ -84.497574, 38.04048 ] } },
{ "type": "Feature", "properties": { "ServiceNam": "Hope Center for Women", "Address": "1524 Versailles Road", "City": "Lexington", "State": "Kentucky", "ZipCode": "40504", "ServiceCat": "Residential Substance Abuse Help", "AddtnlAddr": null, "OperationH": null, "PrimaryPho": "859-252-2002", "SecondaryP": null, "Website": "www.hopectr.org", "addrtype": "street_address", "addrlocat": "ROOFTOP" }, "geometry": { "type": "Point", "coordinates": [ -84.5306536, 38.0484562 ] } },
{ "type": "Feature", "properties": { "ServiceNam": "The Ridge Outpatient Center", "Address": "3050 Rio Dosa Drive", "City": "Lexington", "State": "Kentucky", "ZipCode": "40509", "ServiceCat": "Outpatient Substance Abuse Assessment\/Treatment\/Support", "AddtnlAddr": null, "OperationH": null, "PrimaryPho": "859-269-2324", "SecondaryP": "Toll Free 1-800-753-4673", "Website": null, "addrtype": "street_address", "addrlocat": "ROOFTOP" }, "geometry": { "type": "Point", "coordinates": [ -84.442675, 38.004533 ] } },
{ "type": "Feature", "properties": { "ServiceNam": "Veterans Affairs Medical Center Substance Abuse Treatment Program", "Address": "1101 Veterans Drive", "City": "Lexington", "State": "Kentucky", "ZipCode": "40502", "ServiceCat": "Outpatient Substance Abuse Assessment\/Treatment\/Support", "AddtnlAddr": null, "OperationH": null, "PrimaryPho": "859-233-4511", "SecondaryP": null, "Website": null, "addrtype": "street_address", "addrlocat": "ROOFTOP" }, "geometry": { "type": "Point", "coordinates": [ -84.506738, 38.029732 ] } },
{ "type": "Feature", "properties": { "ServiceNam": "Coleman House", "Address": "1177 Red Mile Place", "City": "Lexington", "State": "Kentucky", "ZipCode": "40504", "ServiceCat": "Emergency Shelters", "AddtnlAddr": null, "OperationH": null, "PrimaryPho": "859-246-4311", "SecondaryP": null, "Website": null, "addrtype": "street_address", "addrlocat": "ROOFTOP" }, "geometry": { "type": "Point", "coordinates": [ -84.5276778, 38.0471719 ] } },
{ "type": "Feature", "properties": { "ServiceNam": "Lexington Rescue Mission Clinic", "Address": "444 Glen Arvin Avenue", "City": "Lexington", "State": "Kentucky", "ZipCode": "40508", "ServiceCat": "Indigent Healthcare", "AddtnlAddr": null, "OperationH": null, "PrimaryPho": "859-381-9600", "SecondaryP": null, "Website": null, "addrtype": "street_address", "addrlocat": "ROOFTOP" }, "geometry": { "type": "Point", "coordinates": [ -84.5041284, 38.0650056 ] } },
{ "type": "Feature", "properties": { "ServiceNam": "Mission Lexington Medical Clinic", "Address": "230 S. Martin Luther King Boulevard", "City": "Lexington", "State": "Kentucky", "ZipCode": "40508", "ServiceCat": "Indigent Healthcare", "AddtnlAddr": null, "OperationH": null, "PrimaryPho": "859-272-0219", "SecondaryP": null, "Website": null, "addrtype": "street_address", "addrlocat": "ROOFTOP" }, "geometry": { "type": "Point", "coordinates": [ -84.498146, 38.0430424 ] } },
{ "type": "Feature", "properties": { "ServiceNam": "Jesse G. Harris Psychological Services Center", "Address": "644 Maxwelton Court", "City": "Lexington", "State": "Kentucky", "ZipCode": "40508", "ServiceCat": "Mental Health Assessment\/Counseling\/Support Groups", "AddtnlAddr": null, "OperationH": null, "PrimaryPho": "859-257-6853", "SecondaryP": null, "Website": null, "addrtype": "street_address", "addrlocat": "ROOFTOP" }, "geometry": { "type": "Point", "coordinates": [ -84.5089872, 38.0363324 ] } },
{ "type": "Feature", "properties": { "ServiceNam": "LFUCG Department of Social Services", "Address": "200 E. Main Street", "City": "Lexington", "State": "Kentucky", "ZipCode": "40507", "ServiceCat": "Mental Health Assessment\/Counseling\/Support Groups", "AddtnlAddr": "Room 328", "OperationH": null, "PrimaryPho": "859-258-3406", "SecondaryP": null, "Website": "www.lexingtonky.gov", "addrtype": "street_address", "addrlocat": "ROOFTOP" }, "geometry": { "type": "Point", "coordinates": [ -84.4956289, 38.044624 ] } },
{ "type": "Feature", "properties": { "ServiceNam": "God's Pantry @ Broadway Christian Church", "Address": "187 North Broadway Street", "City": "Lexington", "State": "Kentucky", "ZipCode": "40507", "ServiceCat": "Food Assistance", "AddtnlAddr": null, "OperationH": "M-F 1-230pm; 6-730pm", "PrimaryPho": null, "SecondaryP": null, "Website": null, "addrtype": "street_address", "addrlocat": "ROOFTOP" }, "geometry": { "type": "Point", "coordinates": [ -84.497991, 38.050768 ] } },
{ "type": "Feature", "properties": { "ServiceNam": "God's Pantry @ Central Christian Church", "Address": "219 East Short Street", "City": "Lexington", "State": "Kentucky", "ZipCode": "40507", "ServiceCat": "Food Assistance", "AddtnlAddr": null, "OperationH": "M-F 2-4pm", "PrimaryPho": null, "SecondaryP": null, "Website": null, "addrtype": "street_address", "addrlocat": "ROOFTOP" }, "geometry": { "type": "Point", "coordinates": [ -84.493467, 38.044942 ] } },
{ "type": "Feature", "properties": { "ServiceNam": "God's Pantry @ Saint Luke United Methodist Church", "Address": "2351 Alumni Drive", "City": "Lexington", "State": "Kentucky", "ZipCode": "40517", "ServiceCat": "Food Assistance", "AddtnlAddr": null, "OperationH": "M-F 1-230pm; 6-730pm", "PrimaryPho": null, "SecondaryP": null, "Website": null, "addrtype": "street_address", "addrlocat": "ROOFTOP" }, "geometry": { "type": "Point", "coordinates": [ -84.4613385, 37.9944857 ] } },
{ "type": "Feature", "properties": { "ServiceNam": "God's Pantry @ Cambridge Drive Pantry", "Address": "1902 Cambridge Drive", "City": "Lexington", "State": "Kentucky", "ZipCode": "40504", "ServiceCat": "Food Assistance", "AddtnlAddr": null, "OperationH": "M-F 6-730pm", "PrimaryPho": null, "SecondaryP": null, "Website": null, "addrtype": "street_address", "addrlocat": "ROOFTOP" }, "geometry": { "type": "Point", "coordinates": [ -84.5435188, 38.0491049 ] } },
{ "type": "Feature", "properties": { "ServiceNam": "Volunteers of America Family Housing Program", "Address": "1400 N. Forbes Road", "City": "Lexington", "State": "Kentucky", "ZipCode": "40511", "ServiceCat": "Housing", "AddtnlAddr": null, "OperationH": null, "PrimaryPho": "859-254-3469", "SecondaryP": null, "Website": "www.voaky.org", "addrtype": "street_address", "addrlocat": "ROOFTOP" }, "geometry": { "type": "Point", "coordinates": [ -84.51986, 38.0647499 ] } },
{ "type": "Feature", "properties": { "ServiceNam": "Planned Parenthood", "Address": "508 W. Second Street", "City": "Lexington", "State": "Kentucky", "ZipCode": "40508", "ServiceCat": "Pregnancy and Parenting", "AddtnlAddr": null, "OperationH": null, "PrimaryPho": "859-252-8494", "SecondaryP": null, "Website": null, "addrtype": "street_address", "addrlocat": "ROOFTOP" }, "geometry": { "type": "Point", "coordinates": [ -84.501086, 38.053717 ] } },
{ "type": "Feature", "properties": { "ServiceNam": "Baby Health Services", "Address": "1590 Harrodsburg Road", "City": "Lexington", "State": "Kentucky", "ZipCode": "40504", "ServiceCat": "Pregnancy and Parenting", "AddtnlAddr": null, "OperationH": "Mon-Fri 7:30am-1pm; Tues-Thurs 7:30am-noon", "PrimaryPho": "859-278-1781", "SecondaryP": null, "Website": "http:\/\/babyhealthlexington.org", "addrtype": "street_address", "addrlocat": "ROOFTOP" }, "geometry": { "type": "Point", "coordinates": [ -84.5251836, 38.0322311 ] } },
{ "type": "Feature", "properties": { "ServiceNam": "West End Community Empowerment Project of Lexington (WECEP)", "Address": "498 Georgetown Street", "City": "Lexington", "State": "Kentucky", "ZipCode": "40508", "ServiceCat": "Education", "AddtnlAddr": "Room 206", "OperationH": null, "PrimaryPho": "859-281-1248", "SecondaryP": null, "Website": null, "addrtype": "street_address", "addrlocat": "ROOFTOP" }, "geometry": { "type": "Point", "coordinates": [ -84.501418, 38.062384 ] } },
{ "type": "Feature", "properties": { "ServiceNam": "Central KY Technical College Adult Education", "Address": "164 Opportunity Way", "City": "Lexington", "State": "Kentucky", "ZipCode": "40511", "ServiceCat": "Education", "AddtnlAddr": null, "OperationH": null, "PrimaryPho": "859-246-6611", "SecondaryP": null, "Website": null, "addrtype": "street_address", "addrlocat": "ROOFTOP" }, "geometry": { "type": "Point", "coordinates": [ -84.5372047, 38.0677208 ] } }
]
}
